from django.contrib import admin
from .models import *
# Register your models here.
admin.site.register(Highlights)
admin.site.register(Festival)
admin.site.register(Sede)
admin.site.register(Evento)
admin.site.register(Proyeccion)
admin.site.register(Taller)
admin.site.register(Conferencia)
admin.site.register(Pelicula)
admin.site.register(Jurado)
admin.site.register(Subscriptor)
admin.site.register(Area)
admin.site.register(MiembroEquipo)
admin.site.register(MiembroStaff)
admin.site.register(BlogPost)
admin.site.register(Contacto)
admin.site.register(RedesSociales)
admin.site.register(Index)