# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='imagen',
            field=models.ImageField(default='static/default.jpg', upload_to='posts'),
        ),
        migrations.AddField(
            model_name='evento',
            name='patrocinadores',
            field=models.ImageField(default='static/default.jpg', upload_to='eventos'),
        ),
        migrations.AddField(
            model_name='jurado',
            name='foto',
            field=models.ImageField(default='static/default.jpg', upload_to='jurado'),
        ),
        migrations.AddField(
            model_name='miembroequipo',
            name='foto',
            field=models.ImageField(default='static/default.jpg', upload_to='equipo'),
        ),
        migrations.AddField(
            model_name='miembrostaff',
            name='foto',
            field=models.ImageField(default='static/default.jpg', upload_to='staff'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='imagen',
            field=models.ImageField(default='static/default.jpg', upload_to='peliculas'),
        ),
        migrations.AddField(
            model_name='sede',
            name='imagen',
            field=models.ImageField(default='static/default.jpg', upload_to='sedes'),
        ),
    ]
