# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 20:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('docu', '0003_miembrostaff_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='fecha_y_hora',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 21, 20, 35, 46, 565005, tzinfo=utc), verbose_name='Fecha y hora'),
            preserve_default=False,
        ),
    ]
