# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docu', '0004_contacto_fecha_y_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='descripcion',
            field=models.CharField(default=0, max_length=3000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='imagen_principal',
            field=models.ImageField(default='static/default.jpg', upload_to='eventos'),
        ),
        migrations.AddField(
            model_name='evento',
            name='logo',
            field=models.ImageField(default='static/default.jpg', upload_to='eventos'),
        ),
    ]
