# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docu', '0005_auto_20160322_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='descripcion',
            field=models.TextField(default=''),
        ),
    ]
