# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 01:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('docu', '0006_auto_20160322_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='autores',
            field=models.CharField(default='-', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2016, 3, 31, 1, 44, 43, 81366, tzinfo=utc), verbose_name='Fecha'),
            preserve_default=False,
        ),
    ]
