# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docu', '0007_auto_20160331_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='jurado',
            name='descripcion',
            field=models.CharField(default='-', max_length=500),
            preserve_default=False,
        ),
    ]
