# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docu', '0008_jurado_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='color_texto_nav',
            field=models.CharField(default='#FFFFFF', max_length=7),
            preserve_default=False,
        ),
    ]
