# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docu', '0009_evento_color_texto_nav'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighlightsFrases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oracion', models.CharField(max_length=100)),
            ],
        ),
    ]
