# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docu', '0010_highlightsfrases'),
    ]

    operations = [
        migrations.CreateModel(
            name='Highlights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='', max_length=100, null=True)),
                ('frase', models.CharField(default='', max_length=100, null=True)),
                ('imagen', models.ImageField(default='static/default.jpg', upload_to='highlights')),
            ],
        ),
        migrations.DeleteModel(
            name='HighlightsFrases',
        ),
    ]
