# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docu', '0011_auto_20160331_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlights',
            name='frase',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='highlights',
            name='titulo',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
