# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docu', '0012_auto_20160331_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='nombre_corto',
            field=models.CharField(default='-', max_length=100),
            preserve_default=False,
        ),
    ]
