# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docu', '0015_auto_20160401_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencia',
            name='costo',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taller',
            name='costo',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
