# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 03:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docu', '0016_auto_20160401_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='es_seleccion_oficial',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='proyeccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='docu.Proyeccion'),
        ),
    ]
