# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docu', '0019_pelicula_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='director',
            field=models.CharField(default='-', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pelicula',
            name='duracion',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pelicula',
            name='year',
            field=models.IntegerField(default=2016),
            preserve_default=False,
        ),
    ]
