# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docu', '0020_auto_20160401_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='nacional',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='trailer',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
