# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docu', '0021_auto_20160401_0406'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='arte',
            field=models.ImageField(blank=True, null=True, upload_to='eventos'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='patrocinadores',
            field=models.ImageField(blank=True, null=True, upload_to='eventos'),
        ),
    ]
