# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docu', '0022_auto_20160403_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='sinopsis',
            field=models.CharField(max_length=1000),
        ),
    ]
