# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docu', '0023_auto_20160403_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedesSociales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(max_length=2000)),
                ('twitter', models.CharField(max_length=2000)),
                ('instagram', models.CharField(max_length=2000)),
                ('mailchimp', models.CharField(max_length=2000)),
            ],
        ),
        migrations.AddField(
            model_name='taller',
            name='link_inscripcion',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
