# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docu', '0024_auto_20160404_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='redessociales',
            name='correo_principal',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
