# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docu', '0025_redessociales_correo_principal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_inicial', models.TextField()),
                ('imagen_parallax_inicial', models.ImageField(default='static/default.jpg', upload_to='index')),
            ],
        ),
    ]
