# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docu', '0027_auto_20160406_0550'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitadoEspecial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tallerista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='duracion',
            field=models.CharField(max_length=30),
        ),
    ]
