# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docu', '0028_auto_20160407_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='taller',
            name='nombre_tallerista',
            field=models.CharField(default='-', max_length=200),
            preserve_default=False,
        ),
    ]
