# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 01:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docu', '0029_taller_nombre_tallerista'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitadoespecial',
            name='evento',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='docu.Evento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tallerista',
            name='evento',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='docu.Evento'),
            preserve_default=False,
        ),
    ]
