# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docu', '0031_auto_20160407_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencia',
            name='costo',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='taller',
            name='costo',
            field=models.CharField(max_length=150),
        ),
    ]
