# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docu', '0032_auto_20160407_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='origen',
            field=models.CharField(default='-', max_length=100),
            preserve_default=False,
        ),
    ]
