# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 19:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('docu', '0034_auto_20160407_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencia',
            name='fecha_y_hora_final',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 7, 19, 13, 26, 474020, tzinfo=utc), verbose_name='Fecha y hora final'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taller',
            name='fecha_y_hora_final',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 7, 19, 13, 29, 716592, tzinfo=utc), verbose_name='Fecha y hora final'),
            preserve_default=False,
        ),
    ]
