# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docu', '0034_auto_20160407_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitadoespecial',
            name='titulo_participacion',
            field=models.CharField(default='-', max_length=100),
            preserve_default=False,
        ),
    ]
