# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docu', '0036_auto_20160410_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='header_proyecciones',
            field=models.ImageField(blank=True, null=True, upload_to='eventos'),
        ),
    ]
