# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docu', '0036_auto_20160410_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='texto_introductorio_seleccion_oficial_nacional',
            field=models.TextField(blank=True, null=True),
        ),
    ]
