# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docu', '0038_evento_texto_introductorio_premios'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='texto_introductorio_sedes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
