# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docu', '0039_evento_texto_introductorio_sedes'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='direccion',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
    ]
