# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docu', '0040_sede_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyeccion',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='docu.Sede'),
        ),
    ]
