# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docu', '0041_auto_20160411_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='tipo',
            field=models.IntegerField(choices=[(0, 'Sede Oficial'), (1, 'Hoteles'), (2, 'Otros')], default=0),
        ),
    ]
