# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 02:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docu', '0042_sede_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='proyeccion_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='peliculas_2', to='docu.Proyeccion'),
        ),
    ]
